// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.14.0
// source: messager.proto

package messager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommunicationType int32

const (
	CommunicationType_Type_External_Client_To_Cluster  CommunicationType = 0
	CommunicationType_Type_External_Cluster_To_Client  CommunicationType = 1
	CommunicationType_Type_Internal_Primary_To_Replica CommunicationType = 2
	CommunicationType_Type_Internal_Replica_To_Primary CommunicationType = 3
)

// Enum value maps for CommunicationType.
var (
	CommunicationType_name = map[int32]string{
		0: "Type_External_Client_To_Cluster",
		1: "Type_External_Cluster_To_Client",
		2: "Type_Internal_Primary_To_Replica",
		3: "Type_Internal_Replica_To_Primary",
	}
	CommunicationType_value = map[string]int32{
		"Type_External_Client_To_Cluster":  0,
		"Type_External_Cluster_To_Client":  1,
		"Type_Internal_Primary_To_Replica": 2,
		"Type_Internal_Replica_To_Primary": 3,
	}
)

func (x CommunicationType) Enum() *CommunicationType {
	p := new(CommunicationType)
	*p = x
	return p
}

func (x CommunicationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommunicationType) Descriptor() protoreflect.EnumDescriptor {
	return file_messager_proto_enumTypes[0].Descriptor()
}

func (CommunicationType) Type() protoreflect.EnumType {
	return &file_messager_proto_enumTypes[0]
}

func (x CommunicationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommunicationType.Descriptor instead.
func (CommunicationType) EnumDescriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{0}
}

// New message type
// Sent to Coordinator 1
type ClientProposeEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID    int64  `protobuf:"varint,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Timestamp   int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Transaction string `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Macs        []byte `protobuf:"bytes,4,opt,name=macs,proto3" json:"macs,omitempty"`
}

func (x *ClientProposeEntry) Reset() {
	*x = ClientProposeEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientProposeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientProposeEntry) ProtoMessage() {}

func (x *ClientProposeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientProposeEntry.ProtoReflect.Descriptor instead.
func (*ClientProposeEntry) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{0}
}

func (x *ClientProposeEntry) GetClientID() int64 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *ClientProposeEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientProposeEntry) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *ClientProposeEntry) GetMacs() []byte {
	if x != nil {
		return x.Macs
	}
	return nil
}

type LeaderPostEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index       int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Signature   []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ClientID    int64  `protobuf:"varint,3,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Transaction string `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp   int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Macs        []byte `protobuf:"bytes,6,opt,name=macs,proto3" json:"macs,omitempty"`
}

func (x *LeaderPostEntry) Reset() {
	*x = LeaderPostEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderPostEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderPostEntry) ProtoMessage() {}

func (x *LeaderPostEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderPostEntry.ProtoReflect.Descriptor instead.
func (*LeaderPostEntry) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderPostEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LeaderPostEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *LeaderPostEntry) GetClientID() int64 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *LeaderPostEntry) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *LeaderPostEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LeaderPostEntry) GetMacs() []byte {
	if x != nil {
		return x.Macs
	}
	return nil
}

type InBatchEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction string `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Timestamp   int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Macs        []byte `protobuf:"bytes,3,opt,name=macs,proto3" json:"macs,omitempty"`
}

func (x *InBatchEntry) Reset() {
	*x = InBatchEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InBatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InBatchEntry) ProtoMessage() {}

func (x *InBatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InBatchEntry.ProtoReflect.Descriptor instead.
func (*InBatchEntry) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{2}
}

func (x *InBatchEntry) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

func (x *InBatchEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InBatchEntry) GetMacs() []byte {
	if x != nil {
		return x.Macs
	}
	return nil
}

type LeaderPostBatchedPostEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchIndex       int64           `protobuf:"varint,1,opt,name=batchIndex,proto3" json:"batchIndex,omitempty"`
	SignatureOnBatch []byte          `protobuf:"bytes,2,opt,name=signatureOnBatch,proto3" json:"signatureOnBatch,omitempty"`
	BatchedEntries   []*InBatchEntry `protobuf:"bytes,4,rep,name=batchedEntries,proto3" json:"batchedEntries,omitempty"`
}

func (x *LeaderPostBatchedPostEntries) Reset() {
	*x = LeaderPostBatchedPostEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderPostBatchedPostEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderPostBatchedPostEntries) ProtoMessage() {}

func (x *LeaderPostBatchedPostEntries) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderPostBatchedPostEntries.ProtoReflect.Descriptor instead.
func (*LeaderPostBatchedPostEntries) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderPostBatchedPostEntries) GetBatchIndex() int64 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *LeaderPostBatchedPostEntries) GetSignatureOnBatch() []byte {
	if x != nil {
		return x.SignatureOnBatch
	}
	return nil
}

func (x *LeaderPostBatchedPostEntries) GetBatchedEntries() []*InBatchEntry {
	if x != nil {
		return x.BatchedEntries
	}
	return nil
}

// Sent to Coordinator 2
type WorkerPostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ClientId  int64  `protobuf:"varint,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *WorkerPostReply) Reset() {
	*x = WorkerPostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerPostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerPostReply) ProtoMessage() {}

func (x *WorkerPostReply) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerPostReply.ProtoReflect.Descriptor instead.
func (*WorkerPostReply) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerPostReply) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WorkerPostReply) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *WorkerPostReply) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type LeaderOrderEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index              int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CombinedSignatures []byte `protobuf:"bytes,2,opt,name=combinedSignatures,proto3" json:"combinedSignatures,omitempty"`
	ClientId           int64  `protobuf:"varint,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *LeaderOrderEntry) Reset() {
	*x = LeaderOrderEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderOrderEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderOrderEntry) ProtoMessage() {}

func (x *LeaderOrderEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderOrderEntry.ProtoReflect.Descriptor instead.
func (*LeaderOrderEntry) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{5}
}

func (x *LeaderOrderEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LeaderOrderEntry) GetCombinedSignatures() []byte {
	if x != nil {
		return x.CombinedSignatures
	}
	return nil
}

func (x *LeaderOrderEntry) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

// Sent to Coordinator 3
type WorkerOrderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	ClientId  int64  `protobuf:"varint,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *WorkerOrderReply) Reset() {
	*x = WorkerOrderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerOrderReply) ProtoMessage() {}

func (x *WorkerOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerOrderReply.ProtoReflect.Descriptor instead.
func (*WorkerOrderReply) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerOrderReply) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WorkerOrderReply) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *WorkerOrderReply) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type LeaderCommitEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index              int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CombinedSignatures []byte `protobuf:"bytes,2,opt,name=combinedSignatures,proto3" json:"combinedSignatures,omitempty"`
	ClientId           int64  `protobuf:"varint,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *LeaderCommitEntry) Reset() {
	*x = LeaderCommitEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderCommitEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderCommitEntry) ProtoMessage() {}

func (x *LeaderCommitEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderCommitEntry.ProtoReflect.Descriptor instead.
func (*LeaderCommitEntry) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderCommitEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LeaderCommitEntry) GetCombinedSignatures() []byte {
	if x != nil {
		return x.CombinedSignatures
	}
	return nil
}

func (x *LeaderCommitEntry) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

// Sent to client
type ClientConfirm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp   int64  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CommitIndex int64  `protobuf:"varint,2,opt,name=commitIndex,proto3" json:"commitIndex,omitempty"`
	TxHash      []byte `protobuf:"bytes,3,opt,name=txHash,proto3" json:"txHash,omitempty"`
}

func (x *ClientConfirm) Reset() {
	*x = ClientConfirm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfirm) ProtoMessage() {}

func (x *ClientConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_messager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfirm.ProtoReflect.Descriptor instead.
func (*ClientConfirm) Descriptor() ([]byte, []int) {
	return file_messager_proto_rawDescGZIP(), []int{8}
}

func (x *ClientConfirm) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientConfirm) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *ClientConfirm) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

var File_messager_proto protoreflect.FileDescriptor

var file_messager_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x63,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x61, 0x63, 0x73, 0x22, 0xb5, 0x01,
	0x0a, 0x0f, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x63, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x6d, 0x61, 0x63, 0x73, 0x22, 0x62, 0x0a, 0x0c, 0x49, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x63, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x61, 0x63, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x1c, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x50,
	0x6f, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4f, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4f,
	0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x3a, 0x0a, 0x0e, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0e, 0x62, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x22, 0x61, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x2e, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x63, 0x6f, 0x6d,
	0x62, 0x69, 0x6e, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x10, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x75, 0x0a, 0x11, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x63, 0x6f, 0x6d, 0x62, 0x69, 0x6e, 0x65, 0x64,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x2a,
	0xa9, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x1f, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x54, 0x6f,
	0x5f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x10, 0x00, 0x12, 0x23, 0x0a, 0x1f, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x54, 0x6f, 0x5f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x10, 0x01, 0x12,
	0x24, 0x0a, 0x20, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x5f, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x54, 0x6f, 0x5f, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x54,
	0x6f, 0x5f, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x10, 0x03, 0x42, 0x12, 0x5a, 0x10, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messager_proto_rawDescOnce sync.Once
	file_messager_proto_rawDescData = file_messager_proto_rawDesc
)

func file_messager_proto_rawDescGZIP() []byte {
	file_messager_proto_rawDescOnce.Do(func() {
		file_messager_proto_rawDescData = protoimpl.X.CompressGZIP(file_messager_proto_rawDescData)
	})
	return file_messager_proto_rawDescData
}

var file_messager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messager_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_messager_proto_goTypes = []interface{}{
	(CommunicationType)(0),               // 0: main.CommunicationType
	(*ClientProposeEntry)(nil),           // 1: main.ClientProposeEntry
	(*LeaderPostEntry)(nil),              // 2: main.LeaderPostEntry
	(*InBatchEntry)(nil),                 // 3: main.InBatchEntry
	(*LeaderPostBatchedPostEntries)(nil), // 4: main.LeaderPostBatchedPostEntries
	(*WorkerPostReply)(nil),              // 5: main.WorkerPostReply
	(*LeaderOrderEntry)(nil),             // 6: main.LeaderOrderEntry
	(*WorkerOrderReply)(nil),             // 7: main.WorkerOrderReply
	(*LeaderCommitEntry)(nil),            // 8: main.LeaderCommitEntry
	(*ClientConfirm)(nil),                // 9: main.ClientConfirm
}
var file_messager_proto_depIdxs = []int32{
	3, // 0: main.LeaderPostBatchedPostEntries.batchedEntries:type_name -> main.InBatchEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messager_proto_init() }
func file_messager_proto_init() {
	if File_messager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientProposeEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderPostEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InBatchEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderPostBatchedPostEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerPostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderOrderEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerOrderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderCommitEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientConfirm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messager_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messager_proto_goTypes,
		DependencyIndexes: file_messager_proto_depIdxs,
		EnumInfos:         file_messager_proto_enumTypes,
		MessageInfos:      file_messager_proto_msgTypes,
	}.Build()
	File_messager_proto = out.File
	file_messager_proto_rawDesc = nil
	file_messager_proto_goTypes = nil
	file_messager_proto_depIdxs = nil
}
